apiVersion: v1
kind: Service
metadata:
  name: pik-service
  labels:
    app: pik-service
spec:
  ports:
    - name: http
      port: 80
  selector:
    app: pik-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pik-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pik-service
  template:
    metadata:
      labels:
        app: pik-service
        version: v1
    spec:
      containers:
        - name: pikapp
          image: pikapp:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: spring_profiles_active
              value: dev
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5